### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by yteraoka** [STNS/libnss#9]
I found that the memory usage of the crond process is getting very large.
Cron daemon call getpwnam() (or similar) function periodically. If non-local management (not exists in /etc/passwd) user's crontab exists then RSS of crond is increased gradually.

OS: CentOS 6, 7
libnss stns version: libnss-stns-v2-2.0.3-2.x86_64 and self compiled (master:740a188ccaef9cb7274df61628d8fb7ce637b58a)

## How to reproduce

nsswitch.conf
```
passwd:     files stns
shadow:     files stns
group:      files stns
```

Check difference of following 2 process's RSS.

```
perl -e 'while(1){getpwnam("root")}'
```

```
perl -e 'while(1){getpwnam("non-local-user")}'
```

**Comment by pyama86** [comment]
Thank you for the report. We will start to fix it.

**Comment by pyama86** [comment]
I fixed your issue.
Can you check https://github.com/STNS/libnss/pull/10 ?

**Comment by yteraoka** [comment]
@pyama86 Thanks, but it seems not fixed.
Could you try with cache disabled? (`cache = false` in /etc/stns/client/stns.conf)

**Comment by pyama86** [comment]
@yteraoka Thanks, I fixed it again.
There was a leak of memory release of http request.

**Comment by yteraoka** [comment]
@pyama86 Thanks again. In the case of local non-https server, it seems fixed.
But I use https server with AWS ALB. In this case it seems not fixed yet.

**Comment by pyama86** [comment]
> But I use https server with AWS ALB. In this case it seems not fixed yet.

oh...
I will also test and https environment.

**Comment by pyama86** [comment]
I confirmed it, but it seemed to be problem free.
I confirmed this way.

```bash
# make docker
$ make build
$ make install
$ mkdir -p /etc/stns/client
# [ロリポップ！マネージドクラウドでSTNSを動かしてみた 〜STNS as a Service〜] https://ten-snapon.com/archives/2057
$ echo 'api_endpoint = "https://stns.lolipop.io/v1"' > /etc/stns/client/stns.conf
$ sed -i 's/sss/stns/g' /etc/nsswitch.conf
$ id pyama
uid=10000(pyama) gid=10000(stns) groups=10000(stns)
$ perl -e 'while(1){getpwnam("non-local-user")}' &
$ watch -n1 -- "ps aux | grep perl"
```

**Comment by pyama86** [comment]
sorry, I forgot https://github.com/STNS/libnss/issues/9#issuecomment-469081264

**Comment by pyama86** [comment]
As far as I looked it seemed to depend on libcurl. Origin was using 7.29 (centos latest), but using 7.64 improved symptoms were seen. I try static link.

**Comment by pyama86** [comment]
Sorry I made you wait.
I made a static link to curl. Now it is no memory leaking.

**Comment by yteraoka** [comment]
@pyama86 Thank you so much. I'll check it later.

**Comment by yteraoka** [comment]
## commit 2cc859c8a5a9978911057fe7932dc980c8534737 (dynamic link)

* CentOS 7 (libcurl-7.29.0-51.el7.x86_64) seems fixed :o:
* CentOS 6 (libcurl-7.19.7-53.el6_9.x86_64) not fixed :x:

## commit 2cfb8a304a7fb1332e35071bfee78462ecd866e9 (static link)

### CentOS 6 (libcurl 7.64.0)

```
gcc -o tmp/libs/stns-key-wrapper \
                tmp/libs/stns.o \
                tmp/libs/stns_key_wrapper.o \
                tmp/libs/parson.o \
                tmp/libs/toml.o \
                /usr/local/curl/lib/libcurl.a \
                -lpthread \
                -lssl \
                -lcrypto \
                -lz \
                -ldl
/usr/local/curl/lib/libcurl.a(libcurl_la-timeval.o): In function `Curl_now':
timeval.c:(.text+0xbf): undefined reference to `clock_gettime'
collect2: ld returned 1 exit status
make: *** [key_wrapper_build] Error 1
```

patch

```
diff --git a/Makefile b/Makefile
index 72ad626..24a4282 100644
--- a/Makefile
+++ b/Makefile
@@ -118,7 +118,8 @@ key_wrapper_build: curl build_dir ## Build nss_stns
                -lssl \
                -lcrypto \
                -lz \
-               -ldl
+               -ldl \
+               -lrt

 integration: build install depsdev ## Run integration test
        @echo "$(INFO_COLOR)==> $(RESET)$(BOLD)Integration Testing$(RESET)"
```

-> Segmentation fault :cry:

```
$ cat /etc/redhat-release
CentOS release 6.10 (Final)
$ rpm -q gcc openssl zlib libcurl glibc
gcc-4.4.7-23.el6.x86_64
openssl-1.0.1e-57.el6.x86_64
zlib-1.2.3-29.el6.x86_64
libcurl-7.19.7-53.el6_9.x86_64
glibc-2.12-1.212.el6.x86_64
```

```
$ cat /etc/stns/client/stns.conf
api_endpoint       = "https://stns.example.com/v1"
auth_token         = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
cache_ttl          = 600
negative_cache_ttl = 60
ssl_verify         = true
cache              = false
request_timeout    = 2
request_retry      = 3
request_locktime   = 10
```

### CentOS 7 (libcurl 7.64.0)

Memory usage is lower than dynamic link one. :+1:

**Comment by pyama86** [comment]
Thank you for much confirmation. I will check about the symptoms of centos6.

**Comment by pyama86** [comment]
I did not do SEVG.
Does SEGV occur with this commit.
https://github.com/STNS/libnss/pull/10/commits/6d5018e9f424c5439cff07a260e8cc4cfdfc1ab8

**Comment by yteraoka** [comment]
I got the SEVG with self-compiled binary.
No problem in libnss-stns-v2-2.3.1-1.x86_64.
Thanks a lot.

**Comment by pyama86** [comment]
Thanks.
Do you have any problem?

**Comment by yteraoka** [comment]
No problem.
